<nav>
    <ul>
        <li><a href="index.php?page=home">Home</a></li>
        <li><a href="index.php?page=about">About</a></li>
        <li><a href="index.php?page=contact">Contact</a></li>
    </ul>
</nav>
    <!-- I would like this to be autogenerated too from the pages that exist -->

